# Generated by Django 4.0.5 on 2022-07-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('lessons', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='test123.jpg', null=True, upload_to='images')),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(null=True, to='home.tag')),
            ],
        ),
    ]
